### ISSUE TITLE
attachements don't get through

### ISSUE THREAD

**Issue by dimpase** [sagemath/trac-to-github#1]
on attempt to import https://trac.sagemath.org/attachment/ticket/7/1790.patch one gets
```
b'Migrate ticket #7 (5 changes): very strange bug with LaurentS'
  created issue Issue(title="very strange bug with LaurentSeriesRing", number=14)
b'  comment by was ( -> )'
b'  attachment by was ( -> 1790.patch)'
b'  resolution by was ( -> fixed)'
Traceback (most recent call last):
  File "/home/dimpase/work/software/trac-to-github/./migrate.py", line 806, in <module>
    convert_issues(source, dest, only_issues = only_issues, blacklist_issues = blacklist_issues)
  File "/home/dimpase/work/software/trac-to-github/./migrate.py", line 568, in convert_issues
    assert attachment is None or change_type == "comment", "an attachment must be followed by a comment"
AssertionError: an attachment must be followed by a comment
```

**Comment by dimpase** [comment]
fixed, sort of, by switching to anonynous access to trac

**Comment by mkoeppe** [comment]
What happens to the attachments in the conversion?

**Comment by dimpase** [comment]
they can either be written on the local disk (this works) or exported as github gists (something that is iffy for binary attachments, and untested by me).

gists are easier to deal with, while these written on the local disk will need to be hosted somewhere.

**Comment by mkoeppe** [comment]
I'd suggest that we host them somewhere. 
How about the Sage file server?

**Comment by dimpase** [comment]
> I'd suggest that we host them somewhere. 
> How about the Sage file server?

we need to get an idea how much space it takes, but probably not too bad.
