### ISSUE TITLE
Minimize event comments

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/trac-to-github#110]
Some of the historic events like "Description changed" are quite prominent and large, while adding relatively little additional information. Thus I propose to minimise them: https://docs.github.com/en/graphql/reference/mutations#minimizecomment

**Comment by mkoeppe** [comment]
Good idea, but I don't think this can be represented in the migration archive.
So this is something that we would need to do after the import using the GitHub API.

**Comment by tobiasdiez** [comment]
So the migration script needs to write a list of all comment ids that need to be minimized, or is there an easy way later to decide which comments to minimize?

**Comment by mkoeppe** [comment]
Sure, it would be more elegant to write out the issue comment URLs to be minimized during the migration, rather than having to parse the issue comments with a regex later.

Is "Description changed" the only type of comment that you'd like to minimize?

What would be the `minimizedReason` (https://docs.github.com/en/graphql/reference/interfaces#minimizable)?  `outdated`? `resolved`?

**Comment by tobiasdiez** [comment]
I would say all "metadata changed" events, e.g. owner, cc added, branch changes, commits, keywords, etc. The current status of these information is displayed in the main issue body.

I vote for "outdated".

**Comment by mkoeppe** [comment]
https://docs.github.com/en/graphql/guides/forming-calls-with-graphql

**Comment by mkoeppe** [comment]
either directly using `curl` or with https://github.com/graphql-python/gql

**Comment by kwankyu** [comment]
If this is easy to do, it would be better done now than later.

**Comment by mkoeppe** [comment]
I looked into this. The list of URLs of issue comments that the migration script saved in `minimized_issue_comments.json` is unfortunately not very useful; the issue comments have been renumbered on import.

I suppose I could use it to narrow it down to the list of issues that contain minimizable issue comments, but I would then have to go through the descriptions and minimize those that match a regex.

I'd say not worth the effort, so I'm marking this as "wishlist".

**Comment by kwankyu** [comment]
It's unfortunate, but I agree that it's not worth the effort.

**Comment by mkoeppe** [comment]
Well OK, I did a first step, after all. I now have the global node_ids of the comments that start with "Description changed".

**Comment by mkoeppe** [comment]
I've minimized a comment! https://github.com/sagemath/sage/issues/10

**Comment by kwankyu** [comment]
Nice! Can this be automated and applied to all issues?

**Comment by mkoeppe** [comment]
Yes, working on it.

**Comment by kwankyu** [comment]
The minimization hides all components of a comment, and thus almost hides the comment itself. Perhaps we may not want to use it for some other changes.

**Comment by mkoeppe** [comment]
That's a great point. I agree.

**Comment by mkoeppe** [comment]
All done!

**Comment by kwankyu** [comment]
Checked some random issues. Well done!

**Comment by kwankyu** [comment]
But there is at least one missed issue:

https://github.com/sagemath/sage/issues/34939

Did you do it for only closed issues?

**Comment by mkoeppe** [comment]
Thanks for catching this. My script forgot to write out the very last batch. Fixed the script in 041a381, and ran this last batch.

**Comment by kwankyu** [comment]
Thanks!
