### ISSUE TITLE
Choose label colors

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/trac-to-github#112]
... so that we can configure the colors of individual labels.

In particular, set the colors of the labels that GitHub predefines (https://github.com/sagemath/trac-to-github/issues/99#issuecomment-1380687042):

![](https://dummyimage.com/100x20/d73a4a&amp;text=+) \#d73a4a bug
![](https://dummyimage.com/100x20/0075ca&amp;text=+) \#0075ca documentation
![](https://dummyimage.com/100x20/cfd3d7&amp;text=+) \#cfd3d7 duplicate
![](https://dummyimage.com/100x20/a2eeef&amp;text=+) \#a2eeef enhancement
![](https://dummyimage.com/100x20/7057ff&amp;text=+) \#7057ff good first issue
![](https://dummyimage.com/100x20/e4e669&amp;text=+) \#e4e669 invalid
![](https://dummyimage.com/100x20/d876e3&amp;text=+) \#d876e3 question
![](https://dummyimage.com/100x20/E81FF9&amp;text=+) \#E81FF9 wishlist item
![](https://dummyimage.com/100x20/ffffff&amp;text=+) \#ffffff wontfix
![](https://dummyimage.com/100x20/008672&amp;text=+) \#008672 help wanted

Need to make color decisions for:
- [ ] component: *math component*
- [ ] component: *other component*
- [ ] duplicate/invalid/wontfix
- [ ] worksforme
- [ ] feature
- [ ] pending
- [ ] priority: minor, critical, blocker, trivial, 
- [ ] status: needs review, positive review, needs info, needs work

https://en.wikipedia.org/wiki/Web_colors

**Comment by kwankyu** [comment]
Don't try to write text in the color band. It does not reflect well the real labels, which will have bold white or black text.

**Comment by mkoeppe** [comment]
As I said in https://github.com/sagemath/trac-to-github/issues/99#issuecomment-1379713901, the `duplicate`, `invalid`, `wontfix` labels could all have the same color. 
Likewise for `duplicate/invalid/wontfix` and `worksforme`. For example:
![](https://dummyimage.com/100x20/cfd3d7&amp;text=+) \#cfd3d7 duplicate, invalid, wontfix, duplicate/invalid/wontfix, worksforme

**Comment by kwankyu** [comment]
Preliminary label colors (needs work):

| group | label | color |  |
| --- | --- | --- | --- |
| component | mathematics  | ![](https://dummyimage.com/100x20/5319e7&amp;text=+) \#5319e7 |
| component | infrastructure (non-math) | ![](https://dummyimage.com/100x20/9875f0&amp;text=+) \#9875f0 | 
| status |  needs review  | ![](https://dummyimage.com/100x20/008672&amp;text=+) \#008672 | 
| status |  positive review  | ![](https://dummyimage.com/100x20/008672&amp;text=+) \#008672 | 
| status |   needs info  | ![](https://dummyimage.com/100x20/40bfac&amp;text=+) \#40bfac | 
| status |  needs work  | ![](https://dummyimage.com/100x20/40bfac&amp;text=+) \#40bfac | 
| type |  duplicate/invalid/wontfix |  ![](https://dummyimage.com/100x20/c2d6d3&amp;text=+) \#c2d6d3 | 
| type | worksforme |  ![](https://dummyimage.com/100x20/c2d6d3&amp;text=+) \#c2d6d3 | 
| type  |  feature  |  ![](https://dummyimage.com/100x20/cfd3d7&amp;text=+) \#cfd3d7 | 
| type  |  pending  |  ![](https://dummyimage.com/100x20/cfd3d7&amp;text=+) \#cfd3d7 | 
| priority |  minor |  ![](https://dummyimage.com/100x20/ffe799&amp;text=+) \#ffe799 | 
| priority |  critical |  ![](https://dummyimage.com/100x20/ffc501&amp;text=+) \#ffc501 | 
| priority |  blocker |  ![](https://dummyimage.com/100x20/ffc501&amp;text=+) \#ffc501 | 
| priority |  trivial |  ![](https://dummyimage.com/100x20/ffe799&amp;text=+) \#ffe799 | 
|  | bug | ![](https://dummyimage.com/100x20/d73a4a&amp;text=+) \#d73a4a | predefined | 
|   | documentation | ![](https://dummyimage.com/100x20/9875f0&amp;text=+) \#9875f0 | predefined |
|  | duplicate | ![](https://dummyimage.com/100x20/cfd3d7&amp;text=+) \#cfd3d7 | predefined | 
|  | enhancement | ![](https://dummyimage.com/100x20/a2eeef&amp;text=+) \#a2eeef | predefined |
|  | good first issue | ![](https://dummyimage.com/100x20/7057ff&amp;text=+) \#7057ff | predefined | 
|  | invalid | ![](https://dummyimage.com/100x20/cfd3d7&amp;text=+) \#cfd3d7 | predefined |
|  |  question | ![](https://dummyimage.com/100x20/d876e3&amp;text=+) \#d876e3 | predefined |
|  | wishlist item | ![](https://dummyimage.com/100x20/E81FF9&amp;text=+) \#E81FF9 | predefined |
|  |  wontfix |  ![](https://dummyimage.com/100x20/cfd3d7&amp;text=+) \#cfd3d7 | predefined |
|  | help wanted | ![](https://dummyimage.com/100x20/008672&amp;text=+) \#008672 | predefined |

**Comment by tobiasdiez** [comment]
A few comments:
- I would not make all status and type comments the same (or almost the same) color. The main advantage of these labels is that you can easily see what action is required by scrolling the list of issues/PRs. So for example "status: needs review" should attract attention because devs should have a look at it, while "status: needs work" can be more quite.
- Some of the "types" seem to be actually a status: duplicate, worksforme, pending
- What is a "trivial" priority?
- I would see the predefined labels as a suggestion from github but not something we need to stick with. So in particular, they should be sorted in the status / type pattern and merged if necessary (e.g. duplicate, wontfix and status: duplicate/invalid/wontfix)

**Comment by mkoeppe** [comment]
> * So for example "status: needs review" should attract attention because devs should have a look at it, while "status: needs work" can be more quite.

excellent point.

**Comment by mkoeppe** [comment]
> * What is a "trivial" priority?

It's the lowest priority on our Trac - for tickets such as simple fixes of typos

**Comment by tobiasdiez** [comment]
So:
- p1: trivial 
- p2: minor
- p3: critial
- p4: blocker

Another scale that I've seen being used is: chore / nice to have / minor / important / urgent.

**Comment by mkoeppe** [comment]
In between "minor" and "critical" we have on Trac the default "major" priority, which I am currently not translating into a label at all.

**Comment by tobiasdiez** [comment]
Also, I don't think having 30 or so component labels is such a big deal. When you assign a label to an issue github gives you a nice autocompletion, and the "status/type/prio" prefix helps you in that since it hides the non-relevant labels.

For example, vscode has more than 400 labels: https://github.com/microsoft/vscode/labels

**Comment by mkoeppe** [comment]
So if the scale from trivial to blocker is represented by different saturations of yellowish orange, then we should also have label for "major".

The idea with suppressing "major" was to reduce noise.
But that only works if "trivial" and "minor" are marked with a color that indicate "more boring than an unlabeled issue"

**Comment by tobiasdiez** [comment]
> In between "minor" and "critical" we have on Trac the default "major" priority, which I am currently not translating into a label at all.

I would suggest to export it and have "no prio label" as a place holder for "not triaged yet". Also you can always delete the major priority later (but adding it to the existing issues is hard).

**Comment by mkoeppe** [comment]
OK,
- [ ] I'll map "major" to a label -- then we can use a middle saturation of yellowish orange for it.

**Comment by mkoeppe** [comment]
> * Some of the "types" seem to be actually a status: duplicate, worksforme, pending

The label "pending" is how I map our special Trac milestone `sage-pending`, which has been used to mark tickets that are either stuck or forgotten.

> * predefined labels [...] should be sorted in the status / type pattern and merged if necessary (e.g. duplicate, wontfix and status: duplicate/invalid/wontfix)

In Trac, we have a special milestone "sage-duplicate/invalid/wontfix" and in addition a "resolution", which is one of the three. (Then there is also a resolution "fixed", which is used for merged tickets.) Label "duplicate/invalid/wontfix" is for tickets that have not been closed yet but have been proposed to be closed with one of these resolutions by moving it to the special milestone. The migration script already does a bit of simplification to the duplicate, invalid, wontfix stuff.

**Comment by kwankyu** [comment]
> .. and the "status/type/prio" prefix helps you in that since it hides the non-relevant labels.

"s: status", "t: type" "p: priority", "c: component " would suffice.

**Comment by kwankyu** [comment]
> I would see the predefined labels as a suggestion from github but not something we need to stick with. So in particular, they should be sorted in the status / type pattern and merged if necessary (e.g. duplicate, wontfix and status: duplicate/invalid/wontfix)

We may retain a subset of these predefined labels and delete the others. Right? 

If we keep a label, then it will be without a prefix (status, type, priority, component) and will have its own color.

**Comment by kwankyu** [comment]
Rewrote "duplicate / invalid / wontfix" and "works for me".

**Comment by tobiasdiez** [comment]
> > I would see the predefined labels as a suggestion from github but not something we need to stick with. So in particular, they should be sorted in the status / type pattern and merged if necessary (e.g. duplicate, wontfix and status: duplicate/invalid/wontfix)
> 
> We may retain a subset of these predefined labels and delete the others. Right?
> 
> If we keep a label, then it will be without a prefix (status, type, priority, component) and will have its own color.

Why do you prefer to have things like "enhancement" "bug" and "documentation" without the "type" prefix? Next to "type: feature" this looks strange to me.  (Also from experience it is often very hard to differentiate between "enhancement" to an existing feature and "feature", which is something completely new - so maybe merge those).

**Comment by mkoeppe** [comment]
The only prefix that we want to use is "component: " -- so that the components show up in one group in the UI.

(The predefined "documentation" should be merged with "component: documentation", of course.)

**Comment by mkoeppe** [comment]
"feature" is converted from the special Trac milestone "sage-feature", which was intended for "big features that will take time". (As with all, I'm not sure how consistently it has been used.)

**Comment by mkoeppe** [comment]
-1 on using any other prefixes. There is no reason for us to educate developers about the differences between "statuses", "resolutions", "types", "priorities". I think it's good enough if developers apply these labels as it feels appropriate.

**Comment by kwankyu** [comment]
> (The predefined "documentation" should be merged with "component: documentation", of course.)

What do you mean by "merged"? We can simply delete the predefined "documentation" label. No?

**Comment by mkoeppe** [comment]
Sure, but maybe we can take its color.

**Comment by kwankyu** [comment]
> -1 on using any other prefixes. 

Wouldn't it be nice to have priority labels grouped together in the dropdown list? If we can order the labels in the dropdown list, we don't need the prefix but it seems not the case...

**Comment by kwankyu** [comment]
Some predefined labels are removed.

**Comment by mkoeppe** [comment]
Do we know the difference between "needs info" and "question"?

**Comment by kwankyu** [comment]
> Why do you prefer to have things like "enhancement" "bug" and "documentation" without the "type" prefix?

No, I don't. 

> Also from experience it is often very hard to differentiate between "enhancement" to an existing feature and "feature", which is something completely new - so maybe merge those.

As Matthias explained, "feature" is close to "wishlist item" rather than "enhancement", which indicates improvement of already existing feature, in trac culture.

We might remove one of "feature" and "wishlist item".  If so, I would keep "wishlist item".

**Comment by tobiasdiez** [comment]
> Do we know the difference between "needs info" and "question"?

I would say needs info signals the status that further information is required to eg replicate a bug. Questions are a type of issues where people ask how to do certain things (which might be better converted to discussions).

**Comment by tobiasdiez** [comment]
> -1 on using any other prefixes. There is no reason for us to educate developers about the differences between "statuses", "resolutions", "types", "priorities". I think it's good enough if developers apply these labels as it feels appropriate.

It's not about educating someone, but to group the labels and make it easier to assign them, e.g you start by typing "status:" and then select the most appropriate one from the filtered list.

**Comment by kwankyu** [comment]
> > Do we know the difference between "needs info" and "question"?
> 
> I would say needs info signals the status that further information is required to eg replicate a bug. Questions are a type of issues where people ask how to do certain things (which might be better converted to discussions).

Would we remove "question" predefined label?

**Comment by tobiasdiez** [comment]
Depends on how you want to treat these kind of issues. If you close them immediately and refer to the correct channel (or migrate them to gh discussions), then I would say you don't need it in my opinion.

**Comment by kwankyu** [comment]
OK. removed "question".

**Comment by mkoeppe** [comment]
Why is "good first issue" removed? Our "beginner" keyword converts to it

**Comment by kwankyu** [comment]
Revived "good first issue" with the color of removed "question".

**Comment by mkoeppe** [comment]
Why do we not use the default colors for "documentation" and "good first issue"?

**Comment by kwankyu** [comment]
> Why do we not use the default colors for "documentation" and "good first issue"?

Why default colors are preferable? Because it is "default" or it looks better?

**Comment by kwankyu** [comment]
Now "needs work" has red color.

**Comment by kwankyu** [comment]
Predefined "documentation" is removed. Note that we also has "component: documentation". All mathematics components have the same color.

**Comment by mkoeppe** [comment]
> Why default colors are preferable? Because it is "default" or it looks better?

Because the colors will be familiar for people who contribute to other GitHub projects that have kept the default colors. (But I have not checked which major projects have kept the default colors.)

**Comment by kwankyu** [comment]
That's the reason that I didn't touch the colors of "bug", "help wanted".

Now that "documentation" is removed, do you want to change the color of "component: documentation" to the default color of "documentation"?

"good first issue" has the same color with "component: infrastructure" labels. Do you still want the default color? Or would you suggest some color not in conflict with other colors?

**Comment by kwankyu** [comment]
I changed the color of "type" labels to darker gray. I expect that white text would look better on the darker background.

**Comment by kwankyu** [comment]
I doubt if "works for me" label would be really useful. Do we have something like it in trac?

**Comment by mkoeppe** [comment]
> I doubt if "works for me" label would be really useful. Do we have something like it in trac?

Yes, we do have it. We translate the "resolution" worksforme to that label.
(Release manager and other Trac admins set a "resolution" when closing a ticket.)

**Comment by mkoeppe** [comment]
> That's the reason that I didn't touch the colors of "bug", "help wanted".

Yes, that's great.

> Now that "documentation" is removed, do you want to change the color of "component: documentation" to the default color of "documentation"?

Yes, that what I was thinking. 
(A rationale of having a clearly recognizable documentation label is that writing / editing documentation is something that is more accessible to non-technical contributors.)

> "good first issue" has the same color with "component: infrastructure" labels. Do you still want the default color? Or would you suggest some color not in conflict with other colors?

Of course, that conflict has to be resolved.

**Comment by mkoeppe** [comment]
I think this remark by Tobias deserves more attention:

> * So for example "status: needs review" should attract attention because devs should have a look at it, while "status: needs work" can be more [subdued]

So by this logic, "needs review" (which needs the attention by a large audience of prospective reviewers) should stand out more (for example, using intense green), whereas "positive review" (which only needs the attention of the release manager, no one else) should also be green, but use less saturation. (In a sense, a "positive review" ticket is about to fade away from the list of open issues -- namely when it is merged.)

**Comment by mkoeppe** [comment]
Also, the color of "blocker" does not make sense to me in the sequence of increasing priorities. Shouldn't it be more red?

**Comment by kwankyu** [comment]
> Also, the color of "blocker" does not make sense to me in the sequence of increasing priorities. Shouldn't it be more red?

There is no "more red" color than `#FF0000`. How about "needs review" yellow, "blocker" red?

**Comment by kwankyu** [comment]
"needs review" now has "intense green" (what I got in google search by the words).

**Comment by kwankyu** [comment]
See real labels here: https://github.com/kwankyu/trac-to-github/labels

**Comment by kwankyu** [comment]
Revived "documentation" predefined label with the default label and "good first issue" with the default color.

Let me know what to do with the conflicts with other labels. Silent ignoring may be an option.

**Comment by kwankyu** [comment]
Resolved color conflicts. Note that we still have "component: documentation" and "documentation" with the same color.

**Comment by kwankyu** [comment]
"needs info" and "needs work" now have the same color. Both seek for author's attention.

**Comment by mkoeppe** [comment]
> > -1 on using any other prefixes.
> 
> Wouldn't it be nice to have priority labels grouped together in the dropdown list? If we can order the labels in the dropdown list, we don't need the prefix but it seems not the case...

I could imagine using "1 – blocker", "2 – critical", "3 – major", ...
This would solve the sorting problem and also be accessible

**Comment by mkoeppe** [comment]
> Note that we still have "component: documentation" and "documentation" with the same color.

But that's the same label, right?

Or did you mean "component: *infrastructure*" and "component: documentation" --- indeed "component: *infrastructure*" needs a different color.

**Comment by kwankyu** [comment]
I meant the predefined label "documentation" which does not have "component: " prefix.

We don't want both the prefixed one and the predefined one. I will remove again the predefined "documentation".

**Comment by mkoeppe** [comment]
> "needs review" now has "intense green" (what I got in google search by the words).

That's not quite what I had in mind.

More like:

![](https://dummyimage.com/100x20/7FFF00&amp;text=+) \#7FFF00 needs review
![](https://dummyimage.com/100x20/DFFFC0&amp;text=+) \#DFFFC0 positive review

**Comment by kwankyu** [comment]
> > > -1 on using any other prefixes.
> > 
> > 
> > Wouldn't it be nice to have priority labels grouped together in the dropdown list? If we can order the labels in the dropdown list, we don't need the prefix but it seems not the case...
> 
> I could imagine using "1 – blocker", "2 – critical", "3 – major", ... This would solve the sorting problem and also be accessible

Big -1. This will defeat what Tobias suggested, searching a label by typing a few initial characters.

**Comment by mkoeppe** [comment]
Well, one just needs to type one digit...

**Comment by kwankyu** [comment]
> More like:
> 
> ![](https://camo.githubusercontent.com/24c370c3467d1a7e07dd5fbf449a73f47ecd242f39287663d49294a4acece843/68747470733a2f2f64756d6d79696d6167652e636f6d2f3130307832302f37464646303026746578743d2b) #7FFF00 needs review ![](https://camo.githubusercontent.com/c58e862cf5590f0766508a6d27c72b0772019552136131f09300fca55186cb55/68747470733a2f2f64756d6d79696d6167652e636f6d2f3130307832302f44464646433026746578743d2b) #DFFFC0 positive review

They look nice. Thanks.

**Comment by kwankyu** [comment]
> Well, one just needs to type one digit...

He wants to type "component: ", see what are available in the filtered list and choose one. In this regard, I still advocate "c:".

**Comment by kwankyu** [comment]
After playing with real labels, I now prefer having no prefix in labels at all, even for components.

**Comment by tobiasdiez** [comment]
> > > > -1 on using any other prefixes.
> > > 
> > > 
> > > Wouldn't it be nice to have priority labels grouped together in the dropdown list? If we can order the labels in the dropdown list, we don't need the prefix but it seems not the case...
> > 
> > 
> > I could imagine using "1 – blocker", "2 – critical", "3 – major", ... This would solve the sorting problem and also be accessible
> 
> Big -1. This will defeat what Tobias suggested, searching a label by typing a few initial characters.

One could also use `p1-blocker` and `p2-critical` etc. Then you can still type `1` and get the correct label.

But honestly, I think we are overcomplicating things here. I would say just choose a consistent convention for now, and some colors that kind of look good. We can easily rename and recolor the labels without any problems, once everyone got a bit of experience with github and new workflows crystalized.

**Comment by kwankyu** [comment]
Now that there is no conflict of colors, currently removed predefined labels may be recovered *after migration*. GitHub users  may find it weird that default labels are missing...

**Comment by mkoeppe** [comment]
> We can easily rename and recolor the labels without any problems

No, that's not completely true -- per https://github.com/sagemath/trac-to-github/issues/99#issuecomment-1379693577, renaming and recoloring compromises the consistency of current labels with the labels that show on old labeling/unlabeling events.

**Comment by mkoeppe** [comment]
Now live in https://34.105.185.241/sagemath/sage-20230113220828/issues?page=3&q=is%3Aissue+is%3Aclosed

**Comment by mkoeppe** [comment]
Updated version (5f15560): https://34.105.185.241/sagemath/sage-20230113225606/issues?page=4&q=is%3Aissue+is%3Aopen

**Comment by tobiasdiez** [comment]
Looks good to me. Two minor points:
- There is a duplicate/invalid/wontfix label that is not used, but [invalid]( https://34.105.185.241/sagemath/sage-20230113225606/labels/invalid) and [duplicate](https://34.105.185.241/sagemath/sage-20230113225606/labels/duplicate) labels that is used
- I would remove the "component" prefix for [component: performance](https://34.105.185.241/sagemath/sage-20230113225606/labels/component%3A%20performance) and [component: refactoring](https://34.105.185.241/sagemath/sage-20230113225606/labels/component%3A%20refactoring). In trac it might have made sense to represent them as components, but they are closer to "bug", "feature" and "enhancement".

**Comment by mkoeppe** [comment]
> * I would remove the "component" prefix for [component: performance](https://34.105.185.241/sagemath/sage-20230113225606/labels/component%3A%20performance) and [component: refactoring](https://34.105.185.241/sagemath/sage-20230113225606/labels/component%3A%20refactoring). In trac it might have made sense to represent them as components, but they are closer to "bug", "feature" and "enhancement".

Done in fdbb42e

**Comment by tobiasdiez** [comment]
Nice, one more observation: The colors of [component: doctest coverage](https://34.105.185.241/sagemath/sage-20230114003037/labels/component%3A%20doctest%20coverage) and maybe [component: misc](https://34.105.185.241/sagemath/sage-20230114003037/labels/component%3A%20misc). And maybe "workforme" can be merged into "invalid".

I'm still in favor of grouping the labels, mostly to make it more convenient to select them in the dropdown list and to provide a consistent sorting in the list of issues (i.e. component first, then priority and then type). But its seems you both don't like it.

**Comment by mkoeppe** [comment]
> The colors of [component: doctest coverage](https://34.105.185.241/sagemath/sage-20230114003037/labels/component%3A%20doctest%20coverage) and maybe [component: misc](https://34.105.185.241/sagemath/sage-20230114003037/labels/component%3A%20misc).

Yes, I'm not very sure about these two either.

**Comment by mkoeppe** [comment]
> One could also use `p1-blocker` and `p2-critical` etc. Then you can still type `1` and get the correct label.

These would be fine with me. Certainly better than just a prefix `p: ` (too cryptic for my taste)

**Comment by mkoeppe** [comment]
I'm very happy with the label colors and component-to-label mappings. Thanks a lot @kwankyu @tobiasdiez

**Comment by kwankyu** [comment]
I am happy with the label colors, but unhappy with the prefix like "p1 - ". But the prefix thing can be decided later after migration and hearing other developers.

**Comment by kwankyu** [comment]
As the label table shows, not only "documentation", but all infrastructure-related components are colored ![](https://dummyimage.com/100x20/0075ca&amp;text=+) \#0075ca. The issues in GSE do not look so.

**Comment by kwankyu** [comment]
At least that was my intention. Is it your intention to color "documentation" distinctly from  other infrastructure labels?

**Comment by mkoeppe** [comment]
> Is it your intention to color "documentation" distinctly from other infrastructure labels?

Yes, this was an adjustment I made intentionally while implementing it.

The idea was that issues in "documentation" components are accessible to a different population of contributors, as writing documentation does not involve programming. The lighter blue indicates that. On the other side, I made the color for the (often technical) contributions to "infrastructure" components a darker blue.

**Comment by kwankyu** [comment]
There are two levels: "documentation" as documents and "documentation" as documentation system. So it seems makes sense but maybe somewhat confusing that we keep both lighter blue "documentation" (predefined label) and the darker blue infrastructure "documentation" (and this maybe renamed to "documentation system" to avoid confusion).

Yes or no?

**Comment by kwankyu** [comment]
What should I change to keep the table 

https://github.com/sagemath/trac-to-github/issues/112#issuecomment-1381241057

up to date?

**Comment by mkoeppe** [comment]
> There are two levels: "documentation" as documents and "documentation" as documentation system.

These two are not distinguished in Trac

**Comment by kwankyu** [comment]
But the labels are also intended for "after migration".

**Comment by mkoeppe** [comment]
> What should I change to keep the table
> 
> [#112 (comment)](https://github.com/sagemath/trac-to-github/issues/112#issuecomment-1381241057)
> 
> up to date?

I made a bunch of smaller changes in the implementation: 
- the colors of the middle priorities ("major" is a bit less orange now, "critical" is a bit more orange)
- duplicate / invalid / wontfix / worksforme are a bit lighter now, so that they are distinguished from "enhancement", "refactoring"

**Comment by kwankyu** [comment]
Then would you make a new table based from mine? Or would we leave the table at it is (as out of date)?

**Comment by mkoeppe** [comment]
I think it's not necessary to introduce a component label for the docbuild system. I think this can be expressed by using "component: build" (or "component: build" and "component: documentation")

**Comment by kwankyu** [comment]
OK.

**Comment by mkoeppe** [comment]
> Then would you make a new table based from mine? Or would we leave the table at it is (as out of date)?

Perhaps it's good enough to point to https://34.105.185.241/sagemath/sage-20230116142640/labels?

**Comment by kwankyu** [comment]
OK. Thanks.
