### ISSUE TITLE
Fine-tuning comment number

### ISSUE THREAD

**Issue by kwankyu** [sagemath/trac-to-github#121]
Recent addition of comment numbers does not work quite well.

I realized that we can get rid of the previous ugly blank space leading comments just by
```
<div id="comment:1"></div>
```
instead of using an anchor tag. 

If we still want to show the comment number (I think we do), we can do
```
<div id="comment:1" align="right">Comment 1</div>
```
Non-bold text seems better as it does not draw attention.

**Comment by kwankyu** [comment]
Here is a sample: https://github.com/kwankyu/trac-to-github/issues/8#comment:1

**Comment by mkoeppe** [comment]
> Non-bold text seems better as it does not draw attention.

I think also in other places, our use of boldface is the wrong way around. In GitHub's events, the values are boldfaced; whereas we boldface the names of the attributes

**Comment by mkoeppe** [comment]
> also in other places, our use of boldface is the wrong way around. In GitHub's events, the values are boldfaced; whereas we boldface the names of the attributes

I've flipped this around now in fa97cb4...e5a504e
