### ISSUE TITLE
Link branch to newly generated issue

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/trac-to-github#13]
Github has the ability to link an issue to a branch (also in a different repo). This seems ideal to link the newly created / imported issue to the existing branch in the trac mirror repo.
 
Docs: https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-a-branch-for-an-issue

I couldn't find docs about this, but its a post request to `https://github.com/<repo>/issues/closing_references?source_id=<id>&source_type=ISSUE`

**Comment by mkoeppe** [comment]
This could be an issue_event of type 
https://docs.github.com/en/developers/webhooks-and-events/events/issue-event-types#referenced or https://docs.github.com/en/developers/webhooks-and-events/events/issue-event-types#closed, setting the  `commit_id`

**Comment by mkoeppe** [comment]
We could obtain the ticket merge commits using `git log --first-parent --author="Release Manager" --merges --grep="^Trac #" --oneline --no-abbrev-commit`

**Comment by mkoeppe** [comment]
That's now  `write-closing-commits.sh`

**Comment by mkoeppe** [comment]
Closing commit annotations are now added as of 1825a63

**Comment by tobiasdiez** [comment]
This is for already merged commits, right? My suggestion was more concerned with linking a branch in sagetrac-mirror (or its renamed version) to an open ticket/issue. This would give an easy way to create a PR for an open issue based on an existing branch.

But this is not high priority and might not be possible with the current api.

**Comment by mkoeppe** [comment]
Ah, right. 

This "linking a branch" business is, I think, a beta feature, and I am not aware of doing that with the migration archive (or the API, for that matter).

**Comment by mkoeppe** [comment]
Confirmed in https://github.com/sagemath/trac-to-github/issues/57#issuecomment-1368734386
