### ISSUE TITLE
Image attachments in issues / issue comments do not work

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/trac-to-github#132]
as seen in https://34.105.185.241/sagemath/sage-20230114144245/issues/34113

**Comment by mkoeppe** [comment]
A downloaded migration archive of trac-to-github has this:
```
attachments_000001.json:
  {
    "type": "attachment",
    "url": "https://user-images.githubusercontent.com/47305845/207409072-4edee502-5c9a-46bf-8e5e-b68d2c97e043.png",
    "issue_comment": "https://github.com/sagemath/trac-to-github/pull/26#issuecomment-1349310298",
    "user": "https://github.com/soehms",
    "asset_name": "image.png",
    "asset_content_type": "image/png",
    "asset_url": "tarball://root/attachments/4edee502-5c9a-46bf-8e5e-b68d2c97e043/image.png",
    "created_at": "2022-12-13T17:57:48Z"
  }

./issue_comments_000004.json:    
"body": "... render it:\r\n\r\n![image](https://user-images.githubusercontent.com/47305845/207409072-4edee502-5c9a-46bf-8e5e-b68d2c97e043.png)\r\n\r\n",

```

Presumably on import, the url will be rewritten to a correct url in the destination.

**Comment by mkoeppe** [comment]
We may need a new method `IssuesConversionHelper.image_link`

**Comment by kwankyu** [comment]
The url of the attachment file is

https://34.105.185.241/sagemath/sage-20230114144245/files/22784/hypercube.png.gz

Why is it 22784? Shouldn't it be 34113 the issue number? In trac, the attachment is "hypercube.png". Here it is "hypercube.png.gz" gzipped file of the original png file. Is this the normal way that attached files work in the migration?

What would the url of the attached file in the final import to Github.com?

**Comment by kwankyu** [comment]
Is this only in ticket description? Does a link to attachment work well in comments? Probably no...

**Comment by soehms** [comment]
Curious! It caught an attachment I've uploaded to PR 26 of this repository. What is the connection with Trac ticket [#34113](https://trac.sagemath.org/ticket/34113)? Or has this been an independent test?

**Comment by mkoeppe** [comment]
> Curious! It caught an attachment I've uploaded to PR 26 of this repository. What is the connection with Trac ticket [#34113](https://trac.sagemath.org/ticket/34113)? Or has this been an independent test?

I downloaded a migration archive of the sagemath/trac-to-github repository for reverse engineering purposes. The data I showed in https://github.com/sagemath/trac-to-github/issues/132#issuecomment-1383255120 comes from there.

**Comment by mkoeppe** [comment]
> Here it is "hypercube.png.gz" gzipped file of the original png file. Is this the normal way that attached files work in the migration?

The importer is very picky about the relation of mime types and filename extensions.
In https://github.com/sagemath/trac-to-github/blob/master/migrate.py#L1658 I replace all files outside of a short list of allowed types with their gzip.

`image/png` and a few other image types are also supposed to work without the gzip workaround, and that's one thing we'll have to change to make the image attachments work.

**Comment by mkoeppe** [comment]
> Is this only in ticket description? Does a link to attachment work well in comments? Probably no...

I've changed the title accordingly.

**Comment by mkoeppe** [comment]
> The url of the attachment file is
> 
> https://34.105.185.241/sagemath/sage-20230114144245/files/22784/hypercube.png.gz
> 
> Why is it 22784? Shouldn't it be 34113 the issue number?

We use `files/ticket34113/hypercube.png.gz` as the filename in the migration archive, but the importer rewrites all these (and the corresponding links it finds). I think 22784 is just a consecutive number of files.

**Comment by mkoeppe** [comment]
New version (no longer gzipped): https://34.105.185.241/sagemath/sage-20230116133759/issues/34113

What's happening is that the image link tries to just use the relative filename "hybercube.png".

**Comment by kwankyu** [comment]
> We may need a new method `IssuesConversionHelper.image_link`

Yes.
