### ISSUE TITLE
Test a read-only configuration for Trac

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/trac-to-github#156]

**Comment by kwankyu** [comment]
Who is the trac admin?

**Comment by mkoeppe** [comment]
I sent a request to sagemath-admins@googlegroups.com two days ago; so far only @dimpase has replied.

Our [Wiki page "Infrastructure"] (https://trac.sagemath.org/wiki/Infrastructure#git.sagemath.orgtrac.sagemath.org) has outdated information only.

The emergency maintenance of Trac last August/September was done by @dimpase @fchapoton @ pipedream, I believe.

**Comment by dimpase** [comment]
To be precise, @fchapoton decided to upgrade trac to a more recent version, with only a partial success. @pipedream and me fixed what was left broken, to allow it to operate normally (or almost normally - the main admin tool `trac-admin` does not work on the host).
