### ISSUE TITLE
Disable pull-request github workflows

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/trac-to-github#157]
Currently, there are a few github workflows triggered by pull-requests (e.g. ci-linux and ci-macos). As they take too much time to be invoked on every pull request, this triggers should be removed.

**Comment by mkoeppe** [comment]
Taking care of this in https://trac.sagemath.org/ticket/34942

**Comment by tobiasdiez** [comment]
What is the plan to get this ticket now merged? If one allows PRs to the new repo (without merging this ticket first), then the ci will be overloaded quite quickly. Can you open a PR with your commits and merge it before opening up the new repo for the "public"?

**Comment by mkoeppe** [comment]
@vbraun Would you be able to prepare a 9.8.rc1 that includes https://trac.sagemath.org/ticket/34942?
