### ISSUE TITLE
Add https://github.com/sagemath organization README

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/trac-to-github#162]
Displayed when people visit https://github.com/sagemath

- [x] Created a preliminary README that serves as a landing page for the people who we sent org membership invitations to.
- [ ] We should explain more clearly what the purposes of the org is (it hosts what..., ....)
- [ ] We should explain what it means to be a member in the org.
     - Related: [#34526](https://trac.sagemath.org/ticket/34526) Broaden the developer's guide to more than just sagelib development
- [ ] Link to the sister org https://gitlab.com/sagemath, which also hosts a few repos. (It needs some cleanup.)

**Comment by kwankyu** [comment]
We may use this to start:

https://github.com/sagemath/sage-archive-2023-02-01/blob/develop/CONTRIBUTING.md

**Comment by mkoeppe** [comment]
Yes, adding material from there seems a good idea

**Comment by kwankyu** [comment]
For inspiration: https://github.blog/2023-02-01-open-sources-impact-on-the-worlds-100-million-developers

**Comment by kwankyu** [comment]
From ChatGPT:

What is the sagemath project?

> SageMath is an open-source mathematical software system that provides a suite of tools for performing various mathematical operations, such as algebra, calculus, number theory, and more. Its role is to provide a comprehensive, free alternative to proprietary mathematical software, allowing for open access to mathematical computation for researchers, students, and the general public. Additionally, SageMath integrates many existing open-source mathematical packages and libraries, making it a convenient and unified platform for mathematical computations.

> SageMath is a free, open-source mathematical software system that integrates various mathematical libraries and supports a broad range of mathematical activities, including algebra, calculus, number theory, cryptography, numerical computation, and more. It provides an interface for users to perform mathematical operations, run simulations, create graphics, and more. It aims to create a viable alternative to proprietary mathematical software such as Matlab, Maple, and Mathematica.

> SageMath is a free open-source mathematics software system that is based on the Python programming language. It covers a wide range of mathematical areas including algebra, calculus, number theory, cryptography, graph theory, and more. It aims to provide an alternative to commercial mathematical software such as Maple, Matlab, and Mathematica. SageMath combines the power of many existing open-source packages and provides an integrated platform for mathematical computing, education, and research.

> SageMath is a free, open-source mathematical software system that covers many aspects of mathematics, including algebra, calculus, number theory, cryptography, numerical computation, and more. It combines the power of many existing open-source packages into a common, easy-to-use interface, and is aimed at both students and professional mathematicians.

> SageMath is a free, open-source mathematics software system that combines various mathematical libraries and tools into a unified framework. It covers a wide range of mathematical areas including algebra, calculus, number theory, cryptography, and more. The goal of the SageMath project is to provide a comprehensive and easy-to-use mathematical software system for students, educators, and researchers.

>SageMath is an open-source mathematics software system that integrates several existing open-source mathematical software packages into a common framework, including features from computer algebra systems, numerical systems, and data visualization. It is aimed at creating a viable free and open-source alternative to proprietary mathematical software, such as Mathematica or Maple.
```

**Comment by kwankyu** [comment]
I had this question myself: Is sagemath "mathematical software" or "mathematics software". I am inclined to the latter.

**Comment by kwankyu** [comment]
From ChatGPT:

What  is the difference in meaning between "mathematical software" and "mathematics software"?

> The difference between "mathematical software" and "mathematics software" is minimal, if any. Both terms are commonly used to describe software programs designed to perform mathematical calculations, simulations, and modeling. However, "mathematical software" might have a slightly broader meaning, as it may refer to software used in a wider range of mathematical fields, such as numerical analysis, linear algebra, and optimization, while "mathematics software" might have a narrower meaning, referring specifically to software used for teaching and learning mathematics.

How smart!

**Comment by kwankyu** [comment]
Processed by a Natural Intelligence:

> SageMath is a free, open-source mathematical software system that is based on the Python programming language. It covers a wide range of mathematical areas including algebra, calculus, number theory, geometry, graph theory, combinatorics and more. It is used to perform calculations, graphing, simulations, and modeling in all mathematical fields, such as physics, cryptography, coding theory, optimization and more.
>
> SageMath started with the aim of providing a free alternative to proprietary mathematical software such as Magma, Maple, Mathematica and Matlab. Thus it combines the power of many existing open-source packages, and provides an integrated platform for mathematical computing, education, and research. Now the SageMath project acts as an umbrella project of open-source mathematical software. 
>
> The developer community of the SageMath project is constantly improving SageMath, and we invite you to help improve the source code, or contribute in your own way. We heartily welcome all kinds of contributions, technical or non-technical, from adding stars to our repositories, reporting bugs or typos, adding comments to issues, or creating Pulling Requests, to donations. We provide a warm and supportive environment in which contributors experience large-scale open-source software development for humanity.

**Comment by kwankyu** [comment]
The current `README.md` is outdated.

**Comment by kwankyu** [comment]
We may update it so that it consists of an introduction (I suggested one version above) and a list of announcements, including a short version of the current readme about mannequin accounts.

**Comment by mkoeppe** [comment]
Sounds good. PR?

**Comment by kwankyu** [comment]
Where is the organization README.md? Is it updated by a PR?

**Comment by kwankyu** [comment]
I got it from `sagemath/.github`.

**Comment by mkoeppe** [comment]
https://github.com/sagemath/.github/pull/3 is merged, thanks!

**Comment by kwankyu** [comment]
Thank you. I forgot the last bullet point (link to gitlab), and there are some typos. I will make another PR later if you do not find a time to fix them.

**Comment by kwankyu** [comment]
Perhaps this is done now?

**Comment by mkoeppe** [comment]
Yes, thank you!
