### ISSUE TITLE
Display a link from each Trac ticket to the converted GitHub Issue

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/trac-to-github#185]
This is the last item from #73.

Likewise from a Trac wiki page to the convert wiki page.

This needs help by a Trac admin

**Comment by dimpase** [comment]
Check it out! Ugly, but works.

**Comment by dimpase** [comment]
![image](https://user-images.githubusercontent.com/1276956/217110194-feacd8ec-bdc0-4fc5-ae1b-cedacfc32f0c.png)

**Comment by dimpase** [comment]
needless to say, you need to hover over the github icon to get the link:
https://trac.sagemath.org/ticket/24700

**Comment by mkoeppe** [comment]
Perfect!
