### ISSUE TITLE
create issues, comments, etc using correct gh accounts

### ISSUE THREAD

**Issue by dimpase** [sagemath/trac-to-github#2]
currently these are created by whyever runs the migration script. We should try to use correct GH account names instead.

**Comment by dimpase** [comment]
@mkoeppe @mezzarobba - to keep this discussion running, and not clogging sage-devel with it.

**Comment by dimpase** [comment]
My next try will be using sagemath GH org owner token to impersonate users in a Team. Not sure if works, but internets say it should. If it does, that's a way to go...

**Comment by roed314** [comment]
Are we aiming to have the trac ticket numbers the same as the github issues?  If so, we'll probably need to delete the existing issues on the sage repo.

**Comment by mkoeppe** [comment]
Yes. If they can't be deleted, we can just start with a fresh repo.

**Comment by roed314** [comment]
While you can [delete issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue) I think it doesn't free up the number.  So we'll probably have to start with a fresh repo.

**Comment by dimpase** [comment]
> While you can [delete issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue) I think it doesn't free up the number. So we'll probably have to start with a fresh repo.

that's not a big deal to remove [Sage repo](https://github.com/sagemath/sage) and add it back  - there is very little in the repo, except the git tree, which is trivial to recreate.

**Comment by dimpase** [comment]
> My next try will be using sagemath GH org owner token to impersonate users in a Team. Not sure if works, but internets say it should. If it does, that's a way to go...

unfortunately, it seems that the creator of the token is baked into the token, and it can't be overrriden. Such a "team" token can be used by the team members, but that's not enough.

I've written to somene at GitHub I know, asking for help - but I'm not sure they'd offer anything.

**Comment by mezzarobba** [comment]
How about the other option I suggested on sage-devel, that is, to create 
new github accounts corresponding to the Sage trac accounts, and let 
people merge them with their main account if they want to?

-- 
Marc

**Comment by dimpase** [comment]
> How about the other option I suggested on sage-devel, that is, to create new github accounts corresponding to the Sage trac accounts, and let people merge them with their main account if they want to?

there is no way for us (at our GitHb support level) to mass-create accounts - one needs Enterprise-level,  I think. Certainly, individuals can create accounts (using an unknown to GitHb email, so we can ask for this (more precisely, for access tokens).

**Comment by dimpase** [comment]
I've also opened a ticket with GitHub support: https://support.github.com/ticket/personal/0/1794579 asking for (reasonably priced) help with the task at hand.

**Comment by dimpase** [comment]
My connection at GitHub, @arfon,  very kindly linked us up with a one of the members of their Developer Relations team, @abbycabs, who should be able to help (I got an automatic email from her, saying "out of office until 21 Sept", so we have to be a bit patient, I guess).

**Comment by mkoeppe** [comment]
@dimpase As discussed today in the developer call, could you describe what kind of github token would be required -- in case some users want to opt-in to having you use it for the conversion.

**Comment by mkoeppe** [comment]
The migration archive route takes care of this, so I'm closing this
