### ISSUE TITLE
Rewrite links http://git.sagemath.org/sage.git/tree/... to github

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/trac-to-github#29]
~~seen on https://github.com/sagemath/trac_to_gh/wiki/functions~~

**Comment by kwankyu** [comment]
Your link doesn't work for me. Would you explain what you mean?

**Comment by mkoeppe** [comment]
It's https://github.com/sagemath/trac_to_gh/wiki/symbolics-functions

**Comment by mkoeppe** [comment]
The link "[sage.functions.other.Function_gamma_inc](http://git.sagemath.org/sage.git/tree/src/sage/functions/other.py#n856)" points to our git server; we should rewrite them to point to sagetrac-mirror

**Comment by kwankyu** [comment]
Do you mean

https://github.com/sagemath/sagetrac-mirror/blob/master/src/sage/functions/other.py#n856

instead of

https://git.sagemath.org/sage.git/tree/src/sage/functions/other.py#n856

?

**Comment by mkoeppe** [comment]
Yes, that's what I had in mind

**Comment by kwankyu** [comment]
Fixed in PR #36

**Comment by mkoeppe** [comment]
Closed by #36
