### ISSUE TITLE
Analyze rate limit

### ISSUE THREAD

**Issue by roed314** [sagemath/trac-to-github#3]
We should think about how long the migration script will take to run under Github's [rate limit](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting), which is 5000 requests per hour, or 15000 for Enterprise users.  I'm not sure if PyGitHub is batching changes in a way that will make this not a problem.

**Comment by dimpase** [comment]
it does have a pause in the loop somewhere

**Comment by roed314** [comment]
Yeah, I saw that.  My concern is that the script seems to be making an API request for each change in the changelog on a ticket.  If an average ticket has 20 comments/updates (rough guess) and Sage has 34500 tickets, we'll need to make 690,000 API requests, which would take 138 hours at a rate limit of 5000 requests per hour.  That's slow but doable, but I may be off in my estimates.

**Comment by dimpase** [comment]
I heard from GitHub support that they have (undocumented) API which is not rate-constrained. 

the biggest sticking block in not here, but with accounts/access tokens.

**Comment by roed314** [comment]
I'll go ahead and close this issue then.
