### ISSUE TITLE
Rewrite explicit links https://trac.sagemath.org/wiki/... 

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/trac-to-github#30]
such as the link to https://trac.sagemath.org/wiki/WikiStart#Surveyingthemathematicalsoftwarelandscape
in https://github.com/sagemath/trac_to_gh/wiki/Upstream#sagemath-upstream-projects

**Comment by kwankyu** [comment]
This rewriting cannot be automated. We need to translate the id `#Surveyingthemathematicalsoftwarelandscape` of trac wiki to  the id `#surveying-the-mathematical-software-landscape` of github wiki. How do we(or rather the script) know where to put spaces?

On the other hand, the rewriting of links seems to belong to the next task following the migration (conversion). Specifically, the final github wiki url is not existent yet.

**Comment by mkoeppe** [comment]
Perhaps in the conversion we should create anchors that are named using the scheme that Trac uses.

**Comment by kwankyu** [comment]
What would be the github repo, the destination of the trac migration? Is it

https://github.com/sagemath/sage

or something new? Is it defined somewhere in the script?

I have been using https://github.com/sagemath/sagetrac-mirror for the script. But this is not it. Right?

**Comment by mkoeppe** [comment]
The wiki would go to https://github.com/sagemath/sage (unless we figure out a different place to host it, such as the Sage website, as discussed in https://trac.sagemath.org/ticket/33725)

**Comment by mkoeppe** [comment]
We do use https://github.com/sagemath/sagetrac-mirror for all the links to branches

**Comment by kwankyu** [comment]
> We do use https://github.com/sagemath/sagetrac-mirror for all the links to branches

Yes, now. But this is not the destination of the migration. Links should point to the destination. No?

**Comment by mkoeppe** [comment]
Only https://github.com/sagemath/sagetrac-mirror has all the named branches. The target repo won't have them.

**Comment by mkoeppe** [comment]
(although in https://github.com/sagemath/sage/wiki/migration-from-trac-to-Git**b#conversion-of-trac-tickets-and-the-trac-wiki-to-github, it is proposed that we rename sagemath/sagetrac-mirror to sagemath/sagetrac-archive)

**Comment by kwankyu** [comment]
Perhaps we need to define the target repo in the target section of the migrate.cfg. Then its value now is  https://github.com/sagemath/sagetrac-mirror, but subject to change as we decide the final destination, if not determined yet.

**Comment by kwankyu** [comment]
> Only https://github.com/sagemath/sagetrac-mirror has all the named branches. The target repo won't have them.

I see. Then we need to deal with two repos `sagetrac-mirror` (for all branches) and the destination repo?

**Comment by kwankyu** [comment]
> (although in https://github.com/sagemath/sage/wiki/migration-from-trac-to-Git**b#conversion-of-trac-tickets-and-the-trac-wiki-to-github, it is proposed that we rename sagemath/sagetrac-mirror to sagemath/sagetrac-archive)

I propose `sagemath/trac-archive`. We tend to use `sage` prefix too much.

**Comment by mkoeppe** [comment]
Yes, git destination and wiki destination url are separate

**Comment by mkoeppe** [comment]
Let's just use sagemath/sagetrac-mirror. I'll simplify the steps at https://github.com/sagemath/sage/wiki/migration-from-trac-to-Git**b#conversion-of-trac-tickets-and-the-trac-wiki-to-github

**Comment by mkoeppe** [comment]
> Perhaps we need to define the target repo in the target section of the migrate.cfg.

Yes, that's a good idea

**Comment by mkoeppe** [comment]
Fixed by #63
