### ISSUE TITLE
Rewrite old ticket titles of the form "[with patch, positive review]"

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/trac-to-github#44]
as seen in https://github.com/sagemath/trac_to_gh/blob/main/Issues-06xxx/6045.md

"positive review" can go into status

**Comment by kwankyu** [comment]
Where is the "status"?

**Comment by kwankyu** [comment]
Just remove it?

**Comment by mkoeppe** [comment]
"Status" is only shown when a ticket is open.
So the idea would be to note a status change when the Trac ticket title is changed to include the prefix "[positive review]"

**Comment by mkoeppe** [comment]
Working on this.
