### ISSUE TITLE
Leave header of "New Commits" blank or not?

### ISSUE THREAD

**Issue by kwankyu** [sagemath/trac-to-github#48]
How about this?

https://github.com/kwankyu/trac_to_gh/wiki/34822#comment:2

It may be easy to implement this by simple substitution.

**Comment by mkoeppe** [comment]
I think it's fine to leave them blank

**Comment by kwankyu** [comment]
Okay. 

We can remove the blank header by using html. See the sample page https://github.com/kwankyu/trac_to_gh/wiki/26855

As you can see there, I changed some "trac generated text" to bold text. How about this?

**Comment by mkoeppe** [comment]
Both ideas sound good

**Comment by mkoeppe** [comment]
Fixed by #50
