### ISSUE TITLE
Porting PRs

### ISSUE THREAD

**Issue by roed314** [sagemath/trac-to-github#5]
Many open trac tickets have an associated branch.  These would most naturally be ported to PRs, but several questions arise:
* How do we number these PRs?  They can't have the same number as the ticket, since this number will be taken by the corresponding issue.  Probably the most natural would be to create a string of PRs for existing (open?) tickets after creating the issues.
* Where are these PRs coming from?  Other branches in the sage repo we're creating?  Forks on github by the user that created the branch?
* Is it possible to create these PRs in a way that the owner of the branch on trac can push to?  If they're branches within the sage repo, giving the creators of the trac branches write access to the sage repo solves the problem.  Forks on Github is probably more natural from a github point of view, but is much more difficult from the perspective of the trac-to-github script.

**Comment by mkoeppe** [comment]
We should document how to continue working on a ticket with existing branch after the migration - #68
