### ISSUE TITLE
Rewrite more git.sagemath.org links

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/trac-to-github#55]
210 issues have unhandled links to git.sagemath.org, which will be broken when we shut down Trac. Example:  https://github.com/sagemath/trac_to_gh/blob/main/Issues-09xxx/9457.md#comment:34

```
$ git grep -l 'git[.]sagemath[.]org' | wc -l
     210
$ git grep -l 'git[.]sagemath[.]org/sage[.]git/diff' | wc -l 
      76
$ git grep -l 'git[.]sagemath[.]org/sage[.]git/log' | wc -l
      33
$ git grep -l 'git[.]sagemath[.]org/sage[.]git/tree' | wc -l
      25
$ git grep -l 'git[.]sagemath[.]org/sage[.]git/commit' | wc -l
      70
```

We want to rewrite such links to equivalent links to https://github.com/sagemath/sagetrac-mirror

**Comment by mkoeppe** [comment]
cgit URLs are defined in https://git.zx2c4.com/cgit/tree/cmd.c#n170

**Comment by mkoeppe** [comment]
Example URLs
- https://git.sagemath.org/sage.git/diff/build/pkgs/qepcad/patches/makefile_no_csh.pa
tch?id=9b43535c1221c86b6e4f17cd36951d88a2c350fb
- http://git.sagemath.org/sage.git/commit/?h=u/slabbe/6637&id=38a82f820d5314890a34d0707851c40ea5eb5b67
- http://git.sagemath.org/sage.git/diff/?id2=fa885d90d609c8311d8fa52deac1340cd558b5a9&id=38a82f820d5314890a34d0707851c40ea5eb5b67
- http://git.sagemath.org/sage.git/tree/Makefile
- http://git.sagemath.org/sage.git/diff/?h=u/gagern/ticket/728&id2=bb7307f0649cfa90916f74c102d1d09a424b759a
- http://git.sagemath.org/sage.git/log/?h=u/niles/ticket/9457
- http://git.sagemath.org/sage.git/tree/build/pkgs/lcalc/patches/lcalc-1.23_default_parameters_2.patch?id=e8b148686cf17804be7354723401bdd84c0a49aa
- http://git.sagemath.org/sage.git/commit/?h=7c4c72596fe2a6de32e61ca578f2e671a51d7962&id=4a6ef0ba815c77321ad2d92d5e4e5e74035e37ce
- http://git.sagemath.org/sage.git/log/?h=u%2Fnbruin%2Fticket%2F15506&qt=range&q=develop..u%2Fnbruin%2Fticket%2F15506

**Comment by kwankyu** [comment]
Related: https://github.com/rahiel/giternity

**Comment by kwankyu** [comment]
> diff:
> 
> * Examples:
>   
>   * https://git.sagemath.org/sage.git/diff/build/pkgs/qepcad/patches/makefile_no_csh.patch?id=9b43535c1221c86b6e4f17cd36951d88a2c350fb

https://github.com/sagemath/sagetrac-mirror/blob/9b43535c1221c86b6e4f17cd36951d88a2c350fb/build/pkgs/qepcad/patches/makefile_no_csh.patch 

>   * http://git.sagemath.org/sage.git/diff/?h=u/gagern/ticket/728&id2=bb7307f0649cfa90916f74c102d1d09a424b759a
>   * http://git.sagemath.org/sage.git/diff/?id2=fa885d90d609c8311d8fa52deac1340cd558b5a9&id=38a82f820d5314890a34d0707851c40ea5eb5b67
> * https://git.zx2c4.com/cgit/tree/ui-diff.c#n384
> 
> commit:
> 
> * Examples:
>   
>   * http://git.sagemath.org/sage.git/commit/?h=u/slabbe/6637&id=38a82f820d5314890a34d0707851c40ea5eb5b67
>   * http://git.sagemath.org/sage.git/commit/?h=7c4c72596fe2a6de32e61ca578f2e671a51d7962&id=4a6ef0ba815c77321ad2d92d5e4e5e74035e37ce
> 
> log:
> 
> * Examples:
>   
>   * http://git.sagemath.org/sage.git/log/?h=u/niles/ticket/9457
>   * http://git.sagemath.org/sage.git/log/?h=u%2Fnbruin%2Fticket%2F15506&qt=range&q=develop..u%2Fnbruin%2Fticket%2F15506
> 
> tree:
> 
> * Examples:
>   
>   * http://git.sagemath.org/sage.git/tree/Makefile
>   * http://git.sagemath.org/sage.git/tree/build/pkgs/lcalc/patches/lcalc-1.23_default_parameters_2.patch?id=e8b148686cf17804be7354723401bdd84c0a49aa

**Comment by mkoeppe** [comment]
> commit:
> 
> * `http://git.sagemath.org/sage.git/commit/?h=u/slabbe/6637&id=38a82f820d5314890a34d0707851c40ea5eb5b67`
> 
> I don't understand why the branch name is there.

It only seems to influence the branch dropdown menu (top right corner). We can ignore it

**Comment by mkoeppe** [comment]
> * `http://git.sagemath.org/sage.git/commit/?h=7c4c72596fe2a6de32e61ca578f2e671a51d7962&id=4a6ef0ba815c77321ad2d92d5e4e5e74035e37ce`
> 
> I don't understand why the tree hash is there.

Same as above
