### ISSUE TITLE
Update the Release Manager scripts

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/trac-to-github#75]

**Comment by tobiasdiez** [comment]
What is now the proposed procedure for merging pull requests? How many reviews are needed, who can merge and what are the required github workflows?

If there is help needed with setting up the required github workflows, I'll hopefully have some time this weekend to help.

**Comment by mkoeppe** [comment]
There are certainly a number of open questions that need to be figured out by the developer community including the release manager @vbraun. 
- For now I would just suggest sticking to using the manual "positive review" label until a different procedure is agreed to. 
- The format of our change logs and Sage tradition require full names for "Author" and "Reviewer", which are not necessarily displayed in the GitHub accounts of all developers. So we either need to figure out a protocol / format how this information should be put in PRs so that scripts/workflows can process it, or decide to relax this requirement
