### ISSUE TITLE
Set up GitHub Enterprise Server instance (free trial)

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/trac-to-github#79]
... in a way that Sage developers can access it (read only)

**Comment by dimpase** [comment]
I just spent hours trying to figure out how to set up this on GCE, to no avail. I don't have many printable words to describe the documentation quality... 

In principle, they should have a VM image one can install, and enable using a trial license. But no, it's an endless maze of meaninglessly unordered, not working, `gcloud` commands, quickly ending up in various rabbit holes.

Not giving up yet, but it's really 🤮

**Comment by mkoeppe** [comment]
Thanks for working on this!!

**Comment by dimpase** [comment]
@mkoeppe - basically, I was  able to start the trial, sent you an invite, download a trial license. (Step 1: Download License
sagemath Evaluation License (45 days)
Organization ID 212138 • Expires 2023-02-19)

But I can't get authorised for "downloading" the software, somehow.
As I click on (Step 2: Download the Appliance
Now that you have your license, head over to the download page to get started with your platform of choice.

[Get the latest release of GitHub Enterprise](https://enterprise.github.com/releases/3.7.2/download)
I get deauthorised. 

That's on Chromium. Perhaps a browser bug, I'll try Safari now.

**Comment by dimpase** [comment]
Same on Safari. Can you try - maybe it's not liking the location (UK) ?

**Comment by mkoeppe** [comment]
In step 2 I can select "GitHub in the Cloud", where it prompts me for "Project" and "ID"

**Comment by dimpase** [comment]
do you remain authorised?

**Comment by mkoeppe** [comment]
Ha, no, it signs me out too on this page

**Comment by dimpase** [comment]
Clicking "Get the latest release of GitHub Enterprise" de-authorises us. 

@abbycabs - how do we go forward from here? 

![image](https://user-images.githubusercontent.com/1276956/210902102-8f96ca75-0ca5-4fd7-8516-7eda4e38930c.png)

**Comment by dimpase** [comment]
tried Chromium@linux, Safari@macos, Chome@chromeos...

**Comment by abbycabs** [comment]
Sorry you're having trouble here! Contacting support is probably the best way to get help. I can escalate your ticket if you're not getting a responses.

**Comment by dimpase** [comment]
Contacted support, we'll see how it goes.

**Comment by dimpase** [comment]
Same picture, submitted https://support.github.com/ticket/personal/0/1955815

**Comment by dimpase** [comment]
OK, it's up now, more or less. Still being re-loaded, though.

**Comment by dimpase** [comment]
@mkoeppe - just emailed you a link to join the trial server

**Comment by dimpase** [comment]
@mkoeppe - just made you an admin there. Beware that a server reboot might change its IP, something I still need to sort out. But hopefully a reboot is not needed for the time being.

**Comment by mkoeppe** [comment]
Thanks, I have successfully accessed it.

**Comment by mkoeppe** [comment]
Can't seem to ssh into the host though as described in https://docs.github.com/en/enterprise-server@3.7/admin/user-management/migrating-data-to-and-from-your-enterprise/preparing-to-migrate-data-to-your-enterprise

**Comment by dimpase** [comment]
OK, now you should be able to, I added your ssh key for admin access there. (It can be done with the site password, which only I know ATM)

**Comment by mkoeppe** [comment]
Thank you, it works!

**Comment by mkoeppe** [comment]
I have a very first import (of 100 issues) ready at https://$HOST_IP/sagemath/sage-import-3/issues; still needs a bit of work

Could you find a secure way to give all Sage developers read-only access to such repos on our server?

**Comment by dimpase** [comment]
At the moment, any SageMath org GitHub user can see https://34.105.185.241/sagemath/sage-import-3
(I think)

Not sure ATM how it can be made fully public (and whether the trial mode even allows it).

**Comment by dimpase** [comment]
oops, no, scratch the latter. I think I found an option to open it up

**Comment by dimpase** [comment]
one can "archive" it, otherwise I don't know how to make issues read-only.

**Comment by mkoeppe** [comment]
It's fine as is, thank you! 

It's readonly for the public because nobody has a user account on our instance. Right?

**Comment by dimpase** [comment]
> nobody has a user account on our instance. Right?

not quite. We have there accounts there of everyone in Sagemath GH org, but they are "suspended" - apart from our 2 ones (it's probably a part of the trial model).

**Comment by mkoeppe** [comment]
They exist because I created them as part of the migration. There are no passwords associated with them.

**Comment by dimpase** [comment]
oh, OK. I may have removed `kini` account - because it popped up for some reason in one of the orgs of repos in some role. Or perhaps I just removed it from all orgs.

**Comment by mkoeppe** [comment]
It doesn't matter. My script will recreate whatever users are needed.

In any case, the migration archive does not contain credential such as passwords, so it does not create users who would be able to authenticate. That's good.
