### ISSUE TITLE
Download migration archive for https://github.com/sagemath/sage, merge with generated archive

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/trac-to-github#82]
- for repository metadata that we can merge with our generated migration archive.
- as backup - see https://trac.sagemath.org/ticket/34624

Per https://docs.github.com/en/enterprise-server@3.6/admin/user-management/migrating-data-to-and-from-your-enterprise/exporting-migration-data-from-githubcom#preparing-the-source-organization-on-github, this needs a token `$MIGRATION_TOKEN` with the `repo` and `admin:org` scopes. (Create as described in https://docs.github.com/en/enterprise-server@3.6/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#creating-a-personal-access-token)

https://docs.github.com/en/rest/migrations/orgs?apiVersion=2022-11-28#start-an-organization-migration

```
curl \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $MIGRATION_TOKEN" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/orgs/sagemath/migrations \
  -d '{"repositories":["sagemath/sage"],"lock_repositories":false,"exclude_git_data":true}'
```

Steps:
- [X] Downloaded
- [X] Added schema, organizations, repository to https://github.com/sagemath/trac-to-github/tree/master/archive
- [x] Fix it up until it imports cleanly

**Comment by mkoeppe** [comment]
It imports well now.

**Comment by mezzarobba** [comment]
Are you keeping the backup up to date? Is it publicly available? (No hurry! I noticed you wanted to take a break from infrastructure work.)

**Comment by mkoeppe** [comment]
No, I am not keeping a backup. I do not have the permanent storage for that.
If you are able to run this as a service, this would be great. The only thing you need is an org-level token as described above. No software is needed -- everything can be done just with `curl`.

**Comment by mezzarobba** [comment]
How much space does it take? Also, I don't think I have the necessary privileges.

**Comment by mkoeppe** [comment]
The migration archive for just the issues that I created was about 5 GB. Something on this order of magnitude will add to the sizes of all the repositories that are in the organization.

@sagemath/core, could @mezzarobba get the necessary privileges for creating a token as described above please?
I opened a Team "backup" for this a while ago, but then I didn't know how to proceed with setting the permissions.
