### ISSUE TITLE
Decide the final location for the Wiki

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/trac-to-github#83]
... so that we rewrite links to the Trac wiki to their final location.

See https://trac.sagemath.org/ticket/33725

**Comment by mkoeppe** [comment]
Perhaps we should 
- define https://www.sagemath.org/wiki as the final location
- set up a Temporary Redirect to https://trac.sagemath.org/wiki for now (@haraldschilly is this easy to do?)
- later set up a Temporary Redirect to https://github.com/sagemath/sage/wiki for use right after the migration
- then figure out how we want to serve the wiki in the long run?

**Comment by kwankyu** [comment]
As there is a separate wiki https://wiki.sagemath.org, it may be difficult to agree on the first bullet point. 

For the last bullet point, this seems hinged upon the eventual merge of both wikis. It would take long (or forever). Then there is nothing to do here.

**Comment by kwankyu** [comment]
Why is this open? Isn't it https://github.com/sagemath/sage/wiki for the on-going migration?

**Comment by mkoeppe** [comment]
Yes, let's consider this settled.
