### ISSUE TITLE
Set up Issue Templates, PR Templates

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/trac-to-github#86]
Issue and PR templates:
[​https://github.com/sagemath/sage-gh-templates-sandbox](https://github.com/sagemath/sage-gh-templates-sandbox)
[​https://github.com/sagemath/sage-gh-templates-sandbox/issues/new/choose](https://github.com/sagemath/sage-gh-templates-sandbox/issues/new/choose)
See [​https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

Discussion: [​https://groups.google.com/g/sage-devel/c/2dKvRwdwVQM](https://groups.google.com/g/sage-devel/c/2dKvRwdwVQM) (2022-10)

**Comment by kwankyu** [comment]
The relationship between issues and PRs is still confusing to me. It seems so to many others. There is no such confusion in trac. 

So how about always requiring an issue for a PR? Then an issue template would correspond to the ticket description box, and a PR template correspond to, more or less, the ticket badges like build&test results and the documentation build results.  Then the roles of an issue and a PR  would be clearly separated.

I fear that allowing a PR without an issue would cause unnecessary confusion...

**Comment by mkoeppe** [comment]
> [...] a PR template correspond to, more or less, the ticket badges like build&test results and the documentation build results

Actually we won't need such ticket badges in the description. The GH Actions checks appear in the Checks tab of a PR (https://github.com/sagemath/website/pull/436) and while running and when failing also as PR events.

**Comment by kwankyu** [comment]
I missed that. Right. Anyway the proposed PR templates here seem to have no substance. Perhaps we need no PR template at all. 

Requiring an issue for an PR may be too much; If the author needs it, then s/he can open an issue using the issue template, and link the issue with the PR.
