### ISSUE TITLE
Check Wiki reference syntax

### ISSUE THREAD

**Issue by soehms** [sagemath/trac-to-github#90]
# Experiments to find Wiki reference syntax that works on issues

Using [MediaWiki](https://www.mediawiki.org/wiki/Help:Links)

* `[[SageMath]]`: [[SageMath]]
* `[[SageMath|SageMath]]`: [[SageMath|SageMath]]
* `[[wiki/SageMath]]`: [[wiki/SageMath]]
* `[[wiki:SageMath]]`: [[wiki:SageMath]]

Using [GitHub Markdown](https://github.github.com/gfm/#links)

* `[SageMath](SageMath)`: [SageMath](SageMath) shown as link, but does not work
* `[Symbolic functions](../wiki/symbolics\ functions)`: [Symbolic functions](../wiki/symbolics\ functions)
* `[Symbolic functions](../wiki/symbolics-functions)`: [Symbolic functions](../wiki/symbolics-functions) goes to `wiki/Home`.

These work:

* `[SageMath](../wiki/SageMath)`: [SageMath](../wiki/SageMath)
* `[Symbolic functions](../wiki/symbolics)`: [Symbolic functions](../wiki/symbolics)

**Comment by mkoeppe** [comment]
I think all of this has been taken care of already
